name: Check Markdown Format

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]

jobs:
  lint-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check markdown files
        run: npx markdownlint-cli@0.49.1 "**/*.md" --ignore node_modules
